const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const {createBackend}=require('./scoring-harness.cjs');
const backend=createBackend();
const alice=backend.token('alice'),bob=backend.token('bob');
let request=0;
const start=(token=alice,extra={})=>backend.call('mdcatStart',token,{mode:'test',contextId:'MDTEST-DEMO-001',requestId:'request-000000000000000'+(++request),...extra});
const ok=result=>{assert.equal(result.success,true,JSON.stringify(result));return result.data;};
const bad=(result,code)=>{assert.equal(result.success,false);assert.equal(result.error.code,code);};
for(const [claims,account]of [[{aud:'other-project'},{}],[{iss:'wrong'},{}],[{exp:1},{}],[{auth_time:1},{}],[{}, {disabled:true}],[{}, {emailVerified:false}],[{firebase:{sign_in_provider:'password'}},{}]])bad(start(backend.token('invalid',claims,account)),'AUTH_REQUIRED');
bad(start('forged-token'),'AUTH_REQUIRED');
backend.setLocked(true);bad(start(),'BUSY');backend.setLocked(false);
backend.props.MDCAT_SCORING_ENABLED='false';bad(start(),'NOT_CONFIGURED');backend.props.MDCAT_SCORING_ENABLED='true';
const first=ok(start(alice,{requestId:'request-repeat-00000000001',UserID:'bob',Score:999}));
assert.equal(first.questions.length,6);
assert.equal(JSON.stringify(first).includes('CorrectOption'),false);
assert.equal(JSON.stringify(first).includes('Private demo explanation'),false);
assert.equal(ok(start(alice,{requestId:'request-repeat-00000000001'})).attemptId,first.attemptId);
assert.equal(backend.rows('MDCAT_Sessions')[0].UserID,'alice');
bad(backend.call('mdcatResume',bob,{attemptId:first.attemptId}),'NOT_FOUND');
bad(backend.call('mdcatSubmit',bob,{attemptId:first.attemptId,answers:[]}),'NOT_FOUND');
bad(backend.call('mdcatResult',alice,{attemptId:first.attemptId}),'NOT_READY');
bad(backend.call('mdcatSubmit',alice,{attemptId:first.attemptId,answers:[{questionId:'foreign',option:'B'}]}),'BAD_REQUEST');
bad(backend.call('mdcatSubmit',alice,{attemptId:first.attemptId,answers:[{questionId:'MDQ-DEMO-001',option:'B'},{questionId:'MDQ-DEMO-001',option:'C'}]}),'BAD_REQUEST');
// The private answer key is snapshotted at start, so edits do not retroactively affect grading.
backend.change('MDCAT_Question_Bank','MDQ-DEMO-001',{CorrectOption:'A'});
backend.advance(25000);
const result=ok(backend.call('mdcatSubmit',alice,{attemptId:first.attemptId,UserID:'bob',Score:999,answers:[{questionId:'MDQ-DEMO-001',option:'B'},{questionId:'MDQ-DEMO-002',option:'A'}]}));
assert.equal(result.correct,1);assert.equal(result.wrong,1);assert.equal(result.unanswered,4);assert.equal(result.score,1);assert.equal(result.percentage,16.67);assert.equal(result.seconds,25);
assert.equal(result.answers.find(row=>row.questionId==='MDQ-DEMO-001').correctOption,'B');
assert.deepEqual(ok(backend.call('mdcatSubmit',alice,{attemptId:first.attemptId,answers:[]})),result);
assert.equal(backend.rows('MDCAT_Attempt_Answers').length,6);
assert.equal(backend.rows('MDCAT_Test_Attempts').length,1);
assert.equal(ok(backend.call('mdcatMyProgress',alice)).reduce((sum,row)=>sum+row.QuestionsAttempted,0),2);
assert.equal(ok(backend.call('mdcatMyResults',bob)).length,0);
assert.equal(ok(backend.call('mdcatMyProgress',bob)).length,0);
bad(backend.call('mdcatResult',bob,{attemptId:first.attemptId}),'NOT_FOUND');
// Freeze first submitted answers in the journal, then recover a partial write without double counting.
const second=ok(start());
backend.failNext('MDCAT_Attempt_Answers');
bad(backend.call('mdcatSubmit',alice,{attemptId:second.attemptId,answers:[{questionId:'MDQ-DEMO-006',option:'D'}]}),'SERVICE_ERROR');
assert.equal(backend.rows('MDCAT_Sessions').find(row=>row.ID===second.attemptId).Status,'Finalizing');
const recovered=ok(backend.call('mdcatSubmit',alice,{attemptId:second.attemptId,answers:[{questionId:'MDQ-DEMO-006',option:'A'}]}));
assert.equal(recovered.correct,1);
assert.equal(backend.rows('MDCAT_Attempt_Answers').length,12);
assert.equal(ok(backend.call('mdcatMyProgress',alice)).reduce((sum,row)=>sum+row.QuestionsAttempted,0),3);
const third=ok(start());backend.failNext('MDCAT_Progress');
bad(backend.call('mdcatSubmit',alice,{attemptId:third.attemptId,answers:[{questionId:'MDQ-DEMO-006',option:'D'}]}),'SERVICE_ERROR');
ok(backend.call('mdcatResume',alice,{attemptId:third.attemptId}));
assert.equal(backend.rows('MDCAT_Attempt_Answers').length,18);
assert.equal(ok(backend.call('mdcatMyProgress',alice)).reduce((sum,row)=>sum+row.QuestionsAttempted,0),4);
// Weighted scores, deductions, unanswered questions and passing threshold.
backend.change('MDCAT_Test_Questions','MDTQ-DEMO-001',{Marks:2});
backend.change('MDCAT_Test_Questions','MDTQ-DEMO-002',{NegativeMarks:0.25});
const weighted=ok(start());
const weightedResult=ok(backend.call('mdcatSubmit',alice,{attemptId:weighted.attemptId,answers:[{questionId:'MDQ-DEMO-001',option:'A'},{questionId:'MDQ-DEMO-002',option:'A'}]}));
assert.equal(weightedResult.score,1.75);assert.equal(weightedResult.maxScore,7);assert.equal(weightedResult.percentage,25);assert.equal(weightedResult.passed,false);
const daily=ok(start(alice,{mode:'daily',contextId:'MDDP-DEMO-001'}));assert.equal(daily.questions.length,2);
const topic=ok(start(alice,{mode:'topic',contextId:'MDT-DEMO-002'}));assert.equal(topic.questions.length,1);
const late=ok(start());backend.advance(331000);bad(backend.call('mdcatSubmit',alice,{attemptId:late.attemptId,answers:[]}),'EXPIRED');
bad(backend.call('mdcatResume',alice,{attemptId:late.attemptId}),'EXPIRED');
backend.change('MDCAT_Test_Questions','MDTQ-DEMO-006',{QuestionID:'missing'});bad(start(),'CONTENT_UNAVAILABLE');
const publicQuestions=JSON.parse(backend.context.doGet({parameter:{action:'mdcatQuestions'}}).getContent());
assert.equal(publicQuestions.success,true);assert.equal(JSON.stringify(publicQuestions).includes('CorrectOption'),false);
const searchIndex=JSON.parse(backend.context.doGet({parameter:{action:'searchIndex'}}).getContent());
assert.equal(searchIndex.success,true);assert.ok(searchIndex.data.some(row=>row.Kind==='MDCAT Question'));
assert.equal(JSON.stringify(searchIndex).includes('CorrectOption'),false);assert.equal(JSON.stringify(searchIndex).includes('Private demo explanation'),false);
const source=fs.readFileSync(path.join(__dirname,'../backend/Code.gs'),'utf8');new vm.Script(source);
const exposed=[...source.matchAll(/^function (\w+)\(/gm)].map(match=>match[1]).filter(name=>!name.endsWith('_'));
assert.deepEqual(exposed,['doGet','doPost']);
assert.equal((source.match(/function getPublicMDCATSubjects_\(/g)||[]).length,1);
console.log('PASS server: provider-validated identity/claims; ownership; no pre-submit keys; server scoring and immutable snapshots; weighted/negative marks; late/invalid/duplicate submissions; idempotency and interrupted-save recovery; progress isolation; test/daily/topic selection; private helper boundary; syntax.');
